-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 19:59:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sales` ;

-- -----------------------------------------------------
-- Schema Sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sales` DEFAULT CHARACTER SET utf8 ;
USE `Sales` ;

-- -----------------------------------------------------
-- Table `Sales`.`Editorials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Editorials` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Editorials` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Books` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ISBN` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pages` INT NULL,
  `published` VARCHAR(45) NULL,
  `Editorial_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Book_Editorial_idx` (`Editorial_id` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Editorial`
    FOREIGN KEY (`Editorial_id`)
    REFERENCES `Sales`.`Editorials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Clients` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Clients` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `identification` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`.`Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Sales` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Client_id` INT NOT NULL,
  `Book_id` INT NOT NULL,
  `quantity` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`, `Client_id`, `Book_id`),
  INDEX `fk_Client_has_Book_Book1_idx` (`Book_id` ASC) VISIBLE,
  INDEX `fk_Client_has_Book_Client1_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Book_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `Sales`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Book_Book1`
    FOREIGN KEY (`Book_id`)
    REFERENCES `Sales`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`.`Authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Authors` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `nickName` VARCHAR(45) NULL,
  `birthDate` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`.`Authorships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales`.`Authorships` ;

CREATE TABLE IF NOT EXISTS `Sales`.`Authorships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Author_id` INT NOT NULL,
  `Book_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Author_id`, `Book_id`),
  INDEX `fk_Author_has_Book_Book1_idx` (`Book_id` ASC) VISIBLE,
  CONSTRAINT `fk_Author_has_Book_Author1`
    FOREIGN KEY (`Author_id`)
    REFERENCES `Sales`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Author_has_Book_Book1`
    FOREIGN KEY (`Book_id`)
    REFERENCES `Sales`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
